# conexao com o Banco (docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/picpay
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# update: cria as tabelas sozinho baseando-se nas classes java
spring.jpa.hibernate.ddl-auto=update

# mostra o SQL no terminal 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 
api.security.token.secret=my-secret-for-test-purposes-123